{
    "name": "Update Invoice GL Account",
    "version": "16.0.0.0.0",
    'author': "Bista Solutions Pvt. Ltd.",
    'website': "https://www.bistasolutions.com",
    'company': 'Bista Solutions Pvt. Ltd.',
    'maintainer': 'Bista Solutions Pvt. Ltd',
    "depends": ['account'],
    "category": "Accounting",
    "data": ['security/update_gl_security.xml',
             'security/ir.model.access.csv',
             'wizard/update_invoice_gl_account_wiz_view.xml',
             'views/account_move.xml',
            ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": 'LGPL-3',
}
