{
    "name": "Macally Reports Extensions",
    "version": "17.0.1.0.0",
    'website': 'https://www.bistasolutions.com',
    'author': 'Bista Solutions Pvt. Ltd.',
    "license": "LGPL-3",
    "category": "",
    "depends": ["base", "account", "sale","stock", "purchase", "l10n_us_check_printing", "stock_picking_batch"],
    "data": [
        'data/paper_format_report.xml',
        'data/ship_via_record.xml',
        'data/vendor_payment_term_records.xml',
        'security/ir.model.access.csv',
        'report/report_header.xml',
        'report/macally_invoice_temp.xml',
        'report/macally_invoice_report.xml',
        'report/report_invoice_inherit.xml',
        'report/report_purchase_inherit.xml',
        'report/purchase_quotation_report.xml',
        'views/purchase_order_views.xml',
        'views/inherit_invoice_views.xml',
        'views/vendor_payment_terms_views.xml',
        'views/ship_via_views.xml',
        'report/ckus_stub_inherit.xml',
        'report/report_picking_batch.xml',
        # 'report/report_package.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
