from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import res_partner
from . import stock_orderpoint
from . import stock_warehouse
from . import product_product
from . import product_template
from . import mrp_bom_line
